service: musashino-calendar-bot
frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-1
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    STAGE: ${self:custom.otherfile.environment.${self:provider.stage}.stage}
    LINE_CHANNEL_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.line_channel_secret}
    LINE_CHANNEL_TOKEN: ${self:custom.otherfile.environment.${self:provider.stage}.line_channel_token}
    LINE_CHANNEL_ID: ${self:custom.otherfile.environment.${self:provider.stage}.line_channel_id}

  apiGateway:
    shouldStartNameWithService: true
  
custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./conf/dev.yml)}
      prod: ${file(./conf/prod.yml)}
  rubyLayer:
    use_docker: true

functions:
  # LINE応答の口
  line_bot:
    handler: app/lambda/line_bot_function.answer
    events:
      - http:
          path: /
          method: post
  # 武蔵野市HPからカレンダー情報を取得
  scraper:
    handler: app/lambda/scraper_function.run
    events: 
      - schedule: rate(1 day)
  # 毎月1日に今月のイベント一覧を送る
  notifier:
    handler: app/lambda/notifier_function.run
    events:
      - schedule: cron(0 0 3 * ? *) # 3日の朝9時に来たらテストOK

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: year_month
            AttributeType: S
        KeySchema:
          -
            AttributeName: year_month
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: musashino-kosodate-events-${self:provider.stage}

plugins:
  - serverless-ruby-layer
